server:
  port: 8848 # 钛金端口,主打稳定

spring:
  application:
    name: codehub
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/codehub?useSSL=false&serverTimezone=UTC
    username: root
    password: xyt
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.xyt.codehub.entity # 别名扫描包
  global-config:
    db-config:
      id-type: auto

logging:
  level:
    cn.xyt: debug

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: cn.xyt.codehub
# knife4j的增强配置
knife4j:
  enable: true
  setting:
    language: zh_cn

sa-token:
  token-style: simple-uuid

task:
  database:
    host: localhost
    port: 3306
    username: root
    password: xyt
    name: codehub
  backup:
    dir: E:\CSUcourse\Three\exp-second\codehub-backup # 备份文件存储目录
