spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/codehub?useSSL=false&serverTimezone=UTC
    username: root
    password: mysql0618

server:
  tomcat:
    #设定tomcat的basedir目录，如果没有指定则使用临时目录
    basedir: /var/www/project-java/tomcat/temp

task:
  database:
    host: localhost
    port: 3306
    username: root
    password: mysql0618
    name: codehub
  backup:
    dir: /var/www/project-java/codehub-backup # 备份文件存储目录

submit:
  dir: /var/www/project-java/codehub-submit
  review:
    command: /usr/bin/sim_java