server:
  port: 8848 # 钛金端口,主打稳定

spring:
  profiles:
    active: dev # 默认启用开发环境

  application:
    name: codehub

  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段

  mail:
    host: smtp.qq.com            # 邮件服务器主机
    port: 587                    # 邮件服务器端口
    username: 3369726918@qq.com   # 发件人邮箱
    password: zysdhixzjmiedabf    # 发件人邮箱密码或应用专用密码
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 10MB

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.xyt.codehub.entity # 别名扫描包
  global-config:
    db-config:
      id-type: auto

logging:
  level:
    cn.xyt: debug

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: cn.xyt.codehub
# knife4j的增强配置
knife4j:
  enable: true
  setting:
    language: zh_cn

sa-token:
  token-style: simple-uuid
